UtilLogger.debug = function(o, g){}
UtilLogger.error = function(o, g, l){}
UtilLogger.log = function(o, g){}
UtilLogger.logc = function(o, g){}
UtilLogger.logi = function(o, g){}
UtilLogger.logr = function(o, g){}
UtilLogger.logy = function(o, g){}
UtilLogger.verbose = function(o, g){}
UtilLogger.warn = function(o, g){}

UtilDate.getNow = function(){}
UtilDate.getNowLocaleString = function(){}
UtilDate.getNowLocaleString__Dash = function(){}
UtilDate.getNowLocaleString__Dash__Milliseconds = function(){}
UtilDate.getNowLocaleString_D = function(){}
UtilDate.getNowLocaleString_H = function(){}
UtilDate.getNowLocaleString_HM = function(){}
UtilDate.getNowString_D = function(){}

UtilFS.appendFile = function(r, n){}
UtilFS.appendFile_Sync = function(t, e){}
UtilFS.check_path = function(t){}
UtilFS.close = function(e){}
UtilFS.close_cb = function(t, e){}
UtilFS.close_Sync = function(t){}
UtilFS.createDirectory = function(t, e){}
UtilFS.createDirectory_BefoeCheck = function(t){}
UtilFS.deleteFile = function(t, e){}
UtilFS.deleteAllFiles_Sync = function(t){}
UtilFS.deleteFile_Sync = function(t){}
UtilFS.deleteFiles_Sync__link_name = function(t, e){}
UtilFS.getList_Directory = function(t){}
UtilFS.getList_File = function(t){}
UtilFS.getList_Folder = function(t){}
UtilFS.getList_FileExtension = function(t, e){}
UtilFS.getList_FE__css = function(t){}
UtilFS.getList_FE__csv = function(t){}
UtilFS.getList_FE__gz = function(t){}
UtilFS.getList_FE__html = function(t){}
UtilFS.getList_FE__js = function(t){}
UtilFS.getList_FE__json = function(t){}
UtilFS.getList_FE__mp3 = function(t){}
UtilFS.getList_FE__tcss = function(t){}
UtilFS.getList_FE__thtml = function(t){}
UtilFS.getList_FE__tjs = function(t){}
UtilFS.getList_FE__tjson = function(t){}
UtilFS.getList_FE__ts = function(t){}
UtilFS.getList_FE__tson = function(t){}
UtilFS.getList_FE__tsv = function(t){}
UtilFS.getList_FE__txml = function(t){}
UtilFS.getList_FE__txt = function(t){}
UtilFS.getList_FE__xml = function(t){}
UtilFS.getList_FE__zip = function(t){}
UtilFS.readDir_Sync = function(t){}
UtilFS.readFile = function(r){}
UtilFS.readFile_cb = function(t, e){}
UtilFS.readFile_Sync = function(t){}
UtilFS.readFile_UTF8_Sync = function(t){}
UtilFS.readFile_UTF8_Sync__JSON = function(t){}
UtilFS.writeFile_UTF8 = function(r, n, i){}
UtilFS.writeFile_UTF8_Sync = function(t, e){}
UtilFS.writeFile_UTF8_Sync__JSON = function(t, e){}
UtilFS.writeFile_UTF8_Sync__JSON_Tab1 = function(t, e){}
UtilFS.writeFile = function(r, n, i){}
UtilFS.writeFile_Sync = function(t, e){}

UtilHttpNodeJS.get = function(t){}
UtilHttpNodeJS.get_cb = function(r, o){}
UtilHttpNodeJS.get_cb__string = function(t, i){}
UtilHttpNodeJS.get_cb__string__utf8 = function(t, i){}
UtilHttpNodeJS.getSync = function(r){}
UtilHttpNodeJS.getSyncJSON = function(e){}
UtilHttpNodeJS.post__native = function(t, n, e, r, o, i){}
UtilHttpNodeJS.post = function(t, n, e, r){}

UtilHttpRequest.check_IP = function(e, t, r){}
UtilHttpRequest.check_IP_N_Response = function(e, t, r){}

UtilHttpResponse.response_header_CORS = function(e, t){}
UtilHttpResponse.response_header_common_json_utf8 = function(e, t){}
UtilHttpResponse.response_header_common_text_utf8 = function(e, t){}
UtilHttpResponse.response_header_contentType = function(e, t, n){}
UtilHttpResponse.response_header_contentType__gz = function(e, t, n){}
UtilHttpResponse.response_200 = function(e, t, n, o){}
UtilHttpResponse.response_200__404 = function(e, t, n, o){}
UtilHttpResponse.response_200_Boolean_False = function(e, t, n, o){}
UtilHttpResponse.response_200_Boolean_True = function(e, t, n, o){}
UtilHttpResponse.response_200_FileStream = function(e, t, n, o, s){}
UtilHttpResponse.response_200_FileStream__Toss = function(e, t, n, o, s){}
UtilHttpResponse.response_200_HTML = function(e, t, n, o){}
UtilHttpResponse.response_200_JSON = function(e, t, n, o){}
UtilHttpResponse.response_200_JSON__Array = function(e, t, n, o){}
UtilHttpResponse.response_200_JSON__Error = function(e, t, n, o){}
UtilHttpResponse.response_200_JSON__Object = function(e, t, n, o){}
UtilHttpResponse.response_200_String = function(e, t, n, o){}
UtilHttpResponse.response_301__google_thdtjsdncom = function(e, t, n){}
UtilHttpResponse.response_301 = function(e, t, n, o){}
UtilHttpResponse.response_400 = function(e, t, n, o){}
UtilHttpResponse.response_400_JSON = function(e, t, n, o){}
UtilHttpResponse.response_403 = function(e, t, n, o){}
UtilHttpResponse.response_403_JSON = function(e, t, n, o){}
UtilHttpResponse.response_404 = function(e, t, n, o){}
UtilHttpResponse.response_404_JSON = function(e, t, n, o){}
UtilHttpResponse.response_416 = function(e, t, n, o){}
UtilHttpResponse.response_500 = function(e, t, n, o){}
UtilHttpResponse.response_500_JSON = function(e, t, n, o){}
UtilHttpResponse.response_501 = function(e, t, n, o){}
UtilHttpResponse.response_501_JSON = function(e, t, n, o){}
UtilHttpResponse.writeHead_response_206 = function(e, t, n, o, s, r){}
UtilHttpResponse.writeHead_response_206__Video = function(e, t, n, o, s){}

UtilHttpsNodeJS.get = function(t){}
UtilHttpsNodeJS.get_cb = function(o, r){}
UtilHttpsNodeJS.get_cb__string = function(t, i){}
UtilHttpsNodeJS.get_cb__string__utf8 = function(t, i){}
UtilHttpsNodeJS.getSync = function(o){}
UtilHttpsNodeJS.getSyncJSON = function(e){}

UtilObject.defineProperty__const = function(t, n, r){}
UtilObject.defineProperty__const__if = function(t, n, r){}

UtilString.deleteNumbers = function(r){}
UtilString.isIPAddress = function(r){}
UtilString.isIPAddress_regexp = function(r){}

UtilStringIPAddress.getIPv4__NodeJS_Request_RemoteAddress = function(e){}
UtilStringIPAddress.isIPAddress = function(e){}
UtilStringIPAddress.isIPAddress_regexp = function(e){}

UtilStringPad_Number.pad_0_1 = function(t){}
UtilStringPad_Number.pad_00_3 = function(t){}

UtilURL.getFileExtensionFromURI = function(e){}
UtilURL.getFileExtensionFromURI_1 = function(e){}
UtilURL.getFilePathFromURI = function(e, r){}
UtilURL.getQueryFromURL = function(e){}
UtilURL.getQueryFromURL_Decode = function(e){}
UtilURL.getQueryObjectFromURL = function(e){}
UtilURL.getQueryObjectFromURL_Decode = function(e){}
UtilURL.getURIFromURL = function(e){}
UtilURL.getURIFromURL_DecodeURI = function(e){}
UtilURL.getURIFromURL_DecodeURIComponent = function(r){}